server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/energy_20231120006?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Zwx3411.!
    driver-class-name: com.mysql.cj.jdbc.Driver

  task:
    scheduling:
      pool:
        size: 5

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: ynu.edu.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT
jwt:
  secret: energy-monitor-2025-secret-key-123456
  expiration: 3600000
  header: Authorization

scheduled:
  data-collect-interval: 5000


logging:
  level:
    ynu.edu: debug
    org.springframework.security: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"